### ISSUE TITLE
IDA crash when I hit Shift+X with mips binary 

### ISSUE THREAD

**Issue by syjzwjj** [darx0r/Reef#1]
I found this plugin crash when I reverse a mips binary and IDA ecounter an crash log.I guess maybe this plugin doesn't support mips binary now?

**Comment by darx0r** [comment]
I did a sanity check on MIPS and it worked for me.
can you add the crash log ?

**Comment by 0xbf00** [comment]
For me, the plugin crashes IDA regardless of the binary used. Presumably this is because the plugin is incompatible with IDA 6.9. Which version of IDA has this plugin been tested with?

I plan to work on this problem myself when I find time for it.

**Comment by darx0r** [comment]
fixed in d75908d0965991eae94862a902cf5de22a353672

**Comment by darx0r** [comment]
issue fixed in d75908d0965991eae94862a902cf5de22a353672
